/** Built-in providers: registry metadata plus a loader for the implementation */

import type { ProviderEntry } from "../core/provider.js";

/**
 * Every provider shipped with the package, in registration order.
 *
 * A provider missing here is invisible to `create()`. `test/unit/registry.test.ts` compares each
 * entry against the class it loads, so metadata cannot drift away from the implementation.
 */
export const builtins: readonly ProviderEntry[] = [
  {
    key: "etherscan",
    chains: [
      "ethereum",
      "base",
      "arbitrum",
      "optimism",
      "polygon",
      "bsc",
      "avalanche",
      "gnosis",
      "linea",
      "berachain",
    ],
    capabilities: {
      balances: true,
      txHistory: true,
      txDetail: true,
      contractInfo: true,
      tokenBalances: true,
      tokenTransfers: true,
      gasData: true,
      blockInfo: true,
    },
    defaultURL: "https://api.etherscan.io/v2/api",
    load: () => import("./etherscan.js").then((m) => m.Etherscan),
  },
  {
    key: "blockscout",
    chains: [
      "ethereum",
      "base",
      "arbitrum",
      "optimism",
      "polygon",
      "gnosis",
      "linea",
      "scroll",
      "zksync",
      "avalanche",
    ],
    capabilities: {
      balances: true,
      txHistory: true,
      txDetail: true,
      contractInfo: true,
      tokenBalances: true,
      tokenTransfers: true,
      gasData: true,
      blockInfo: true,
    },
    defaultURL: "https://eth.blockscout.com",
    load: () => import("./blockscout.js").then((m) => m.Blockscout),
  },
  {
    key: "blockchair",
    chains: ["bitcoin", "ethereum"],
    capabilities: {
      balances: true,
      txHistory: true,
      txDetail: true,
      contractInfo: false,
      tokenBalances: false,
      tokenTransfers: false,
      gasData: false,
      blockInfo: true,
    },
    defaultURL: "https://api.blockchair.com",
    load: () => import("./blockchair.js").then((m) => m.Blockchair),
  },
  {
    key: "mempool",
    chains: ["bitcoin", "litecoin"],
    capabilities: {
      balances: true,
      txHistory: true,
      txDetail: true,
      contractInfo: false,
      tokenBalances: false,
      tokenTransfers: false,
      gasData: true,
      blockInfo: true,
    },
    defaultURL: "https://mempool.space",
    load: () => import("./mempool.js").then((m) => m.Mempool),
  },
  {
    key: "solscan",
    chains: ["solana"],
    capabilities: {
      balances: true,
      txHistory: true,
      txDetail: true,
      contractInfo: false,
      tokenBalances: false,
      tokenTransfers: false,
      gasData: false,
      blockInfo: true,
    },
    defaultURL: "https://pro-api.solscan.io/v2.0",
    load: () => import("./solscan.js").then((m) => m.Solscan),
  },
  {
    key: "helius",
    chains: ["solana"],
    capabilities: {
      balances: false,
      txHistory: true,
      txDetail: true,
      contractInfo: false,
      tokenBalances: false,
      tokenTransfers: false,
      gasData: false,
      blockInfo: false,
    },
    defaultURL: "https://mainnet.helius-rpc.com",
    load: () => import("./helius.js").then((m) => m.Helius),
  },
  {
    key: "ton",
    chains: ["ton"],
    capabilities: {
      balances: true,
      txHistory: true,
      txDetail: false,
      contractInfo: false,
      tokenBalances: false,
      tokenTransfers: false,
      gasData: false,
      blockInfo: false,
    },
    defaultURL: "https://tonapi.io",
    load: () => import("./ton.js").then((m) => m.Ton),
  },
  {
    key: "tronscan",
    chains: ["tron"],
    capabilities: {
      balances: true,
      txHistory: true,
      txDetail: true,
      contractInfo: false,
      tokenBalances: false,
      tokenTransfers: false,
      gasData: false,
      blockInfo: true,
    },
    defaultURL: "https://apilist.tronscanapi.com",
    load: () => import("./tronscan.js").then((m) => m.Tronscan),
  },
  {
    key: "aptos",
    chains: ["aptos"],
    capabilities: {
      balances: false,
      txHistory: false,
      txDetail: false,
      contractInfo: false,
      tokenBalances: false,
      tokenTransfers: false,
      gasData: false,
      blockInfo: false,
    },
    load: () => import("./aptos.js").then((m) => m.Aptos),
  },
  {
    key: "blockberry",
    chains: ["sui"],
    capabilities: {
      balances: true,
      txHistory: true,
      txDetail: false,
      contractInfo: false,
      tokenBalances: false,
      tokenTransfers: false,
      gasData: false,
      blockInfo: false,
    },
    defaultURL: "https://api.blockberry.one/sui",
    load: () => import("./blockberry.js").then((m) => m.Blockberry),
  },
];
